[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["pt100/#"]
  username = "telegraf"
  password = "${MQTT_TELEGRAF_PASS}"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "pt100"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "resistance"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "fault"
      type = "int"
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "pt100/+"
    tags  = "_/sensor_id"

[[outputs.influxdb_v3]]
  urls = ["http://influxdb3:8181"]
  token = "${INFLUX_TOKEN}"
  database = "${INFLUXDB_DATABASE}"
