apiVersion: 1
datasources:
  - name: InfluxDB
    uid: pt100-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb3:8181
    jsonData:
      version: InfluxQL
      httpMode: POST
      dbName: ${INFLUXDB_DATABASE}
    secureJsonData:
      password: ${INFLUX_TOKEN}
    editable: true
